In [1]:
import tensorflow_hub as hub
import tensorflow_text as text

In [2]:
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [3]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"

In [4]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [6]:
text_test = ["nice movie indeed","I love python programming"]

In [7]:
text_preprocessed = bert_preprocess_model(text_test)

In [8]:
text_preprocessed

{'input_word_ids': <tf.Tensor: shape=(2, 128), dtype=int32, numpy=
 array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     

In [9]:
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [10]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [11]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [12]:
bert_model = hub.KerasLayer(encoder_url)

In [15]:
bert_result = bert_model(text_preprocessed)

In [16]:
bert_result.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [17]:
bert_result['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7916381 , -0.21401832,  0.49778825, ...,  0.2445495 ,
        -0.47325817,  0.8175386 ],
       [-0.91703737, -0.47904378, -0.78609234, ..., -0.61709267,
        -0.71006066,  0.9218161 ]], dtype=float32)>

In [18]:
bert_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07296449,  0.08557408,  0.14468797, ..., -0.09657122,
          0.08712933,  0.07727157],
        [ 0.17859878, -0.19009805,  0.5033989 , ..., -0.05882023,
          0.32694456, -0.15579712],
        [ 0.18710195, -0.4340848 , -0.48876804, ..., -0.15496314,
          0.00146329, -0.24453509],
        ...,
        [ 0.12061725,  0.12885782,  0.4645589 , ...,  0.07372758,
          0.17414734,  0.1653504 ],
        [ 0.07949206, -0.01211711,  0.5025364 , ...,  0.13790885,
          0.20990229,  0.0061568 ],
        [-0.0722513 , -0.2831484 ,  0.59030867, ...,  0.47551867,
          0.16647315, -0.08913229]],

       [[-0.07882559,  0.36319512, -0.21078998, ..., -0.17139482,
          0.16300714,  0.67262447],
        [ 0.2789909 ,  0.43677995, -0.35746235, ..., -0.04435221,
          0.38312963,  0.5891633 ],
        [ 1.2044512 ,  1.0724102 ,  0.48439223, ...,  0.24897118,
          0.40699008,  0.40525174],
        ...,

In [19]:
len(bert_result['encoder_outputs'])

12

In [20]:
bert_result['encoder_outputs'][0]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.12900528,  0.00634984, -0.03611606, ...,  0.0500397 ,
          0.06157248, -0.02655075],
        [ 1.1753212 ,  1.2141372 ,  1.1571534 , ...,  0.11636336,
         -0.35857785, -0.40499875],
        [ 0.03887827,  0.53851604, -0.21081674, ...,  0.21843228,
          0.7259829 , -1.1156806 ],
        ...,
        [-0.07592269, -0.25426006,  0.70761186, ...,  0.505343  ,
         -0.18874134,  0.15022251],
        [-0.1606901 , -0.28087366,  0.57618016, ...,  0.5275664 ,
         -0.11131994,  0.02877958],
        [-0.04423197, -0.20283395,  0.5910138 , ...,  0.8134705 ,
         -0.39078286, -0.02602799]],

       [[ 0.18901862,  0.02744296, -0.06512041, ..., -0.00614002,
          0.15051518,  0.0316597 ],
        [ 0.591519  ,  0.7588235 , -0.07236904, ...,  0.6190585 ,
          0.8292969 ,  0.1618711 ],
        [ 1.4458436 ,  0.44604033,  0.4099121 , ...,  0.48273885,
          0.62682503,  0.1347506 ],
        ...,

In [21]:
bert_result['encoder_outputs'][-1]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07296449,  0.08557408,  0.14468797, ..., -0.09657122,
          0.08712933,  0.07727157],
        [ 0.17859878, -0.19009805,  0.5033989 , ..., -0.05882023,
          0.32694456, -0.15579712],
        [ 0.18710195, -0.4340848 , -0.48876804, ..., -0.15496314,
          0.00146329, -0.24453509],
        ...,
        [ 0.12061725,  0.12885782,  0.4645589 , ...,  0.07372758,
          0.17414734,  0.1653504 ],
        [ 0.07949206, -0.01211711,  0.5025364 , ...,  0.13790885,
          0.20990229,  0.0061568 ],
        [-0.0722513 , -0.2831484 ,  0.59030867, ...,  0.47551867,
          0.16647315, -0.08913229]],

       [[-0.07882559,  0.36319512, -0.21078998, ..., -0.17139482,
          0.16300714,  0.67262447],
        [ 0.2789909 ,  0.43677995, -0.35746235, ..., -0.04435221,
          0.38312963,  0.5891633 ],
        [ 1.2044512 ,  1.0724102 ,  0.48439223, ...,  0.24897118,
          0.40699008,  0.40525174],
        ...,

In [23]:
bert_result['encoder_outputs'][-1]==bert_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>